import esbuild from 'esbuild';
import process from 'node:process';
import fs from 'node:fs';
import path from 'node:path';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const prod = process.argv[2] === 'production';
const outDir = 'dist';

fs.mkdirSync(outDir, { recursive: true });

/** Copy manifest.json (root) + styles.css (src) alongside main.js so `dist/` is a ready-to-load plugin. */
const copyStaticAssets = {
  name: 'copy-static-assets',
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      fs.copyFileSync('manifest.json', path.join(outDir, 'manifest.json'));
      fs.copyFileSync(path.join('src', 'styles.css'), path.join(outDir, 'styles.css'));
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2022',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.join(outDir, 'main.js'),
  minify: prod,
  loader: {
    '.wasm': 'binary',
  },
  plugins: [copyStaticAssets],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}

